name: Setup
description: Install Node and dependencies
runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: npm
    - name: Install dependencies
      shell: bash
      run: npm ci
